# PteroStats config
# If you need help, join our discord server here: https://discord.gg/zv6maQRah3

# Bot Configuration
token: 'Put bot token here'
bot_status:
    enable: false
    text: 'Hosting Panel'
    type: 'WATCHING' # can be 'WATCHING', 'PLAYING', 'LISTENING', or 'COMPETING'. for 'STREAMING' is not working for now

# Discord Channel and Refresh Time Configuration
channel: '1038135400184696954'
refresh: 10

# Panel Configuration
panel:
    url: 'panel.unbenchedhosting.online'
    key: 'ptla_VJIW4jtUJOVgbzckKcxItDJvMMQasUrsusvY9NkgnNO'

# Message Configuration
# set to false if you want to disable option
message:
    content: false
    attachment: false # If you enable attachment on message it upload the attachment first before sending or editing message and it will delay the stats

embed:
    title: 'PteroStats'
    color: '5865F2'
    description: 'Next update {{time}}' # You can use {{time}} to make "in X seconds" time format
    footer: 'By Hirzi#8701'
    timestamp: true
    thumbnail: false
    image: false
    field:
        enable: false
        title: 'Custom Field'
        description: 'Custom Field' # You can use {{time}} to make "in X seconds" time format

# Message Button Configuration
button:
    enable: true
    btn1:
        label: 'PteroStats'
        url: 'https://github.com/HirziDevs/PteroStats'
    btn2:
        label: ''
        url: ''
    btn3:
        label: ''
        url: ''
    btn4:
        label: ''
        url: ''
    btn5:
        label: ''
        url: ''

# Status Message Configuration
status:
    online: ':green_circle: Online'
    offline: ':red_circle: Offline'

# Nodes Resource
nodes_resource:
    blacklist: [] # You can add node id to remove the node from status embed (Example: "blacklist: [1]")
    enable: false
    servers: true
    location: true
    allocations: true
    unit: 'gb' # You can use "gb", "mb", "tb", or "percent"

# Panel Users and Servers
panel_resource:
    enable: true
    servers: true
    users: true
